version: '3.7'
services:
  chemistry:
    build: ../chemistry_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../chemistry_project/:/usr/src/chemistry_project/
    ports:
      - 8000:8000
    env_file:
      - ../chemistry_project/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=il
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=django_dev
volumes:
  postgres_data: